["一步一步来"]
Usage = "对任何问题都能获得更全面的结果"
MainIdea = "Let's think step by step"
Scenario = ["通用"]

["Step-Back-Thinking"]
Usage = "能显著提升密集推理任务的思考效果"
MainIdea = "后退提问是一种思考策略，意在从更宏观或更基础的角度去理解和分析一个特定的问题或情境；回答问题时，抽象问题，得到更高纬度概念和原理，再用这些知识推理并解决问题。"
Strategy = [
    "首先确定问题的核心概念。例如，如果问题涉及到物理学中的力，那么可能需要后退到基础的力的定义和原理。",
    "问题的范围：尝试识别问题的范围和上下文。这有助于确定后退的深度。有些问题可能只需要稍微后退一步，而其他问题可能需要深入到基础原理。",
    "历史和背景：对于一些问题，了解其历史背景和发展可能会有助于提出恰当的后退问题。",
    "原理和假设：明确当前问题的基础原理和假设。这可以帮助确定应该从哪些方面后退。"
]
Scenario = ["通用", "复杂问题"]
Steps = [
    "每当用户输入一个问题，给出至少3个符合<策略>的可选<后退提问>并分别回答",
    "组合回答的结果，决定是否需要继续后退提问，如果需要，重复步骤1",
    "最后，整合每个部分的结论，以解决整个问题"
]

["BRTR-Principle"]
Usage = "一种构建高效率的提示词的原则"
MainIdea = "BRTR原则包含明确背景（Background）、定义角色（Role，也包含 Skills）、划分任务（Task）和呈现需求（Request）几个步骤，以构建高效率的提示词。"
Strategy = [
    "具体而直接地与用户沟通，明确 AI 设计的目标和初衷",
    "使用后退思维技巧对问题的领域、背景、上下文、历史等进行深入分析，明确设计的关键要素",
    "针对用户需求和个人的专业知识，通过具体例子展示创建的AI提示词如何帮助用户实现他们的目标",
    "以详细步骤说明设计的过程，让用户了解设计的过程",
    "在首次创建提示词时，对每个技能的具体步骤进行两次优化，确保每个技能都拥有详细的执行步骤，并提供最终输出的标准格式"
]
Scenario = ["Prompting"]
Steps = [
    "与用户具体而直接地沟通，明确 AI 设计的目标和初衷",
    "使用后退思维技巧进行问题的深入分析，明确设计的关键要素",
    "针对用户需求和个人的专业知识，通过具体例子展示如何帮助用户",
    "详细解释设计的过程",
    "在首次创造提示词时，优化每个技能的具体步骤",
    "确保每个技能都有详细的执行步骤，并提供最终输出的标准格式"
]

["创建领域专家"]
Usage = "当用户提供一个特定领域或主题时，通过以下步骤来创建一个该领域的专家"
MainIdea = "通过深入理解特定领域或主题的核心概念、搜索相关资料、用简洁明了的语言解释复杂概念、制定出完整的对话流程、为每个任务制定具体步骤等方法，创建领域专家。"
Strategy = [
    "深入理解用户提供的领域或主题的核心概念和思想",
    "搜索和阅读相关的学术文献、专业网站、权威报告等，建立全面的专业知识理解",
    "用简洁明了的语言解释复杂或抽象的概念，使其易于理解",
    "从用户的角度思考，确定他们可能会对这个领域有哪些问题或需求，通过问答的形式制定出一套完整的对话流程",
    "根据用户的需求和自己的理解，为每个任务和目标制定出具体步骤，明确定义AI的角色和责任",
    "在每一步任务中，详细说明AI需要执行的具体行动",
    "给出一个详细的执行步骤和操作流程，明确的要求交付内容的形式，并给出一个预期的输出样例"
]
Scenario = ["Prompting"]
Steps = [
    "深入理解用户提供的领域或主题的核心概念和思想",
    "搜索和阅读相关的资料，建立全面的专业知识理解",
    "用简洁明了的语言解释复杂或抽象的概念",
    "从用户的角度思考，确定他们可能会对这个领域有哪些问题或需求，通过问答的形式制定对话流程",
    "根据用户的需求和自己的理解，为每个任务和目标制定具体步骤，定义AI的角色和责任",
    "详细说明AI需要执行的具体行动，包括如何使用相关知识和技能",
    "给出详细的执行步骤和操作流程，明确交付内容的形式，并给出预期的输出样例"
]